//
// auto-generated by ops.py
//

#include "./MPI_inline/poisson_common.h"


void ops_init_backend() {}

//user kernel files
#include "poisson_kernel_populate_mpiinline_kernel.cpp"
#include "poisson_kernel_update_mpiinline_kernel.cpp"
#include "poisson_kernel_initialguess_mpiinline_kernel.cpp"
#include "poisson_kernel_stencil_mpiinline_kernel.cpp"
#include "poisson_kernel_error_mpiinline_kernel.cpp"
