//
// auto-generated by ops.py
//

int xdim0_advec_mom_kernel_copy_back;
int xdim1_advec_mom_kernel_copy_back;


//user function



void advec_mom_kernel_copy_back_c_wrapper(
  double * restrict vel1_temp_p,
  double * restrict vel1_p,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      const ptr_double vel1_temp = { vel1_temp_p + n_x*1 + n_y * xdim0_advec_mom_kernel_copy_back*1, xdim0_advec_mom_kernel_copy_back};
      ptr_double vel1 = { vel1_p + n_x*1 + n_y * xdim1_advec_mom_kernel_copy_back*1, xdim1_advec_mom_kernel_copy_back};
      
        OPS_ACC(vel1, 0, 0) = OPS_ACC(vel1_temp, 0, 0);

    }
  }
}
