//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_poisson_kernel_stencil;
int xdim1_poisson_kernel_stencil;
int xdim2_poisson_kernel_stencil;

//user function
inline 
void poisson_kernel_stencil(const ptr_double u,
  const ptr_double f,
  ptr_double u2) {



  OPS_ACC(u2, 0,0) = ((OPS_ACC(u, -1,0)+OPS_ACC(u, 1,0))*dx*dx
                     + (OPS_ACC(u, 0,-1)+OPS_ACC(u, 0,1))*dy*dy
                     - dx*dx*dy*dy*OPS_ACC(f, 0,0))
                     /(2.0*(dx*dx+dy*dy));
}


void poisson_kernel_stencil_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  int x_size, int y_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a2)
  #pragma acc loop
  #endif
  for ( int n_y=0; n_y<y_size; n_y++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_x=0; n_x<x_size; n_x++ ){
      const ptr_double ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_poisson_kernel_stencil*1*1, xdim0_poisson_kernel_stencil};
      const ptr_double ptr1 = {  p_a1 + n_x*1*1 + n_y*xdim1_poisson_kernel_stencil*1*1, xdim1_poisson_kernel_stencil};
      ptr_double ptr2 = {  p_a2 + n_x*1*1 + n_y*xdim2_poisson_kernel_stencil*1*1, xdim2_poisson_kernel_stencil};
      poisson_kernel_stencil( ptr0,
          ptr1,ptr2 );

    }
  }
}
