//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_advec_mom_kernel_copy_back;
int xdim1_advec_mom_kernel_copy_back;

//user function

inline void advec_mom_kernel_copy_back(const ACC<double> vel1_temp,
  ACC<double> vel1)
{
        OPS_ACC(vel1, 0, 0) = OPS_ACC(vel1_temp, 0, 0);
}


void advec_mom_kernel_copy_back_c_wrapper(
  double *p_a0,
  double *p_a1,
  int x_size, int y_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1)
  #pragma acc loop
  #endif
  for ( int n_y=0; n_y<y_size; n_y++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_x=0; n_x<x_size; n_x++ ){
      const ptr_double ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_advec_mom_kernel_copy_back*1*1, xdim0_advec_mom_kernel_copy_back};
      ptr_double ptr1 = {  p_a1 + n_x*1*1 + n_y*xdim1_advec_mom_kernel_copy_back*1*1, xdim1_advec_mom_kernel_copy_back};
      advec_mom_kernel_copy_back( ptr0, ptr1);
    }
  }
}
